# 1. PyTorch Fundamentals Exercises : Read about [torch.cuda.manual_seed](https://pytorch.org/docs/stable/generated/torch.cuda.manual_seed.html)



### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size = (7,7))
X ,X.shape

(tensor([[0.0135, 0.1610, 0.7289, 0.0344, 0.6874, 0.9325, 0.2620],
         [0.6110, 0.2654, 0.9502, 0.6104, 0.6895, 0.0075, 0.9252],
         [0.0225, 0.8939, 0.4816, 0.1785, 0.7450, 0.8583, 0.8248],
         [0.2242, 0.0908, 0.3099, 0.1765, 0.0700, 0.3585, 0.5981],
         [0.8781, 0.4246, 0.0709, 0.2455, 0.0271, 0.0194, 0.6894],
         [0.5870, 0.8448, 0.8619, 0.8487, 0.7560, 0.2479, 0.5083],
         [0.0348, 0.0822, 0.4606, 0.9948, 0.7628, 0.7273, 0.1291]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
Y = torch.rand(size = (1,7))
# Perform matrix multiplication
Z = torch.matmul(X,Y.T)
Z ,Z.shape

(tensor([[2.0903],
         [2.2666],
         [2.6956],
         [1.0275],
         [1.0565],
         [2.7961],
         [1.8296]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
seed = 1234
if torch.cuda.is_available():
   torch.cuda.manual_seed(seed)
else:
    print("CUDA is not available. Please check your GPU setup.")


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(12340)
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
tensor_A = torch.rand(size = (2,3) ,device=device)
tensor_B = torch.rand(size = (2,3) ,device=device)
tensor_A ,tensor_B

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
tensor_C = tensor_A @ tensor_B.T
tensor_C ,tensor_C.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
mx = tensor_C.max()
# Find min
mn = tensor_C.min()
mx  , mn

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
mx_idx = tensor_C.argmax()
# Or arg_max = torch.argmax(tensor_C)

# Find arg min
mn_idx = tensor_C.argmin()
# Or arg_min = torch.argmin(tensor_C)

mx_idx ,mn_idx

(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [20]:
# Set seed
torch.manual_seed = 7

# Create random tensor
tensor_rand = torch.rand(size = (1,1,1,10))

# Remove single dimensions
tensor_rand_squeeze = tensor_rand.squeeze()

# Print out tensors and their shapes
print(tensor_rand ,tensor_rand.shape)
print(tensor_rand_squeeze ,tensor_rand_squeeze.shape)

tensor([[[[0.1524, 0.0514, 0.1817, 0.3981, 0.0995, 0.4846, 0.8170, 0.3140,
           0.2900, 0.4500]]]]) torch.Size([1, 1, 1, 10])
tensor([0.1524, 0.0514, 0.1817, 0.3981, 0.0995, 0.4846, 0.8170, 0.3140, 0.2900,
        0.4500]) torch.Size([10])
