**Date Published: Decemper 17, 2024 ,
Author: Adnan Alare**f

In [1]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu121


# ◍ Introduction to Tensors.

## 🔸 Create scaler tensor.

In [ ]:
scaler = torch.tensor(6)
scaler, scaler.ndim , scaler.shape ,scaler.item()

# Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number.

(tensor(6), 0, torch.Size([]), 6)

## 🔸 Create vector tensor.

In [ ]:
vector = torch.tensor([7,8])
vector ,vector[0] ,vector[1] ,vector.ndim, vector.shape

(tensor([7, 8]), tensor(7), tensor(8), 1, torch.Size([2]))

**Note:** If you want to convert a specific element in the vector to a number, you can index the tensor and call .item()  

* **.item()** is necessary to extract the scalar value as a Python number.  

* Ensure that the reduction operation results in a tensor with a single element before calling **.item()**.

In [ ]:
# Convert the second element to a scalar
vector[1].item() # Output: 8

8

## 🔸 Create Matrix tensor.

In [ ]:
matrix = torch.tensor([[1,2,5],[3,4,9],[5,6,7]])
matrix ,matrix.ndim , matrix.shape

(tensor([[1, 2, 5],
         [3, 4, 9],
         [5, 6, 7]]),
 2,
 torch.Size([3, 3]))

In [ ]:
# Convert the element in [1][2] to a scalar
matrix[1][2].item() # Output: 9

9

In [ ]:
tensor_3d = torch.tensor([[[1,2,3],[-1,5,6],[17,8,9]]])
tensor_3d , tensor_3d.ndim , tensor_3d.shape

(tensor([[[ 1,  2,  3],
          [-1,  5,  6],
          [17,  8,  9]]]),
 3,
 torch.Size([1, 3, 3]))

In [ ]:
# To access the element at position (0, 0, 1) by use .item()
tensor_3d[0,0,1].item() # Output: 2

2

**Note:** use `.flatten()` if you want to treat the 3D tensor as a 1D vector for operations like sorting or indexing.

In [ ]:
flatten_tensor = tensor_3d.flatten()
print(f"Flatten Tensor : {flatten_tensor}") # Output: [1,2,3,-1,5,6,17,8,9]

# Accessing the first element of the flattened tensor
first_element = flatten_tensor[0].item()

print(f"First Element : {first_element}")

Flatten Tensor : tensor([ 1,  2,  3, -1,  5,  6, 17,  8,  9])
First Element : 1


## 🔸 Random tensors.

In [ ]:
# Create a float32 random tensor from [0,1] of size (3, 4)
random_tensor = torch.rand(size = (3,4) ,dtype = torch.float32)
random_tensor , random_tensor.ndim , random_tensor.shape

(tensor([[0.3493, 0.1509, 0.7322, 0.7512],
         [0.9953, 0.8399, 0.1716, 0.3287],
         [0.9329, 0.1988, 0.8565, 0.3763]]),
 2,
 torch.Size([3, 4]))

In [ ]:
# Create a float64 random tensor from [0,1] of size (3, 4)
random_tensor1 = torch.rand(size = (3,4) ,dtype = torch.float64)

random_tensor1 , random_tensor1.ndim , random_tensor1.shape

(tensor([[0.7192, 0.2307, 0.3309, 0.7059],
         [0.8675, 0.9852, 0.4502, 0.0688],
         [0.5937, 0.9873, 0.2284, 0.0930]], dtype=torch.float64),
 2,
 torch.Size([3, 4]))

In [ ]:
# Create a intger8/16/32/64 random tensor from [low,high] of size (3, 4)
intger_random_tensor = torch.randint(low=0 ,high=10

                                     ,size=(3,4) ,dtype = torch.int64)

intger_random_tensor , intger_random_tensor.ndim , intger_random_tensor.shape

(tensor([[2, 0, 2, 5],
         [0, 9, 0, 6],
         [5, 1, 5, 6]]),
 2,
 torch.Size([3, 4]))

## 🔸 Zeros and Ones.

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))

zeros ,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))

ones , ones.dtype ,ones.device

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 device(type='cpu'))

## 🔸 Createing a range tensors and tensors-like.

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future
print(zero_to_ten_deprecated)

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start = 0, end = 10 ,step = 1)
print(zero_to_ten)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


<ipython-input-58-2ce73a16bcd8>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


In [ ]:
# Creating tensors zeros-like
zeros_like = torch.zeros_like(input = zero_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 🔸 Tensors operations.

In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
# add 10 to tensor
Addition = tensor + 10  # Or
addition = torch.add(tensor , 10)

Addition , addition

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [ ]:
Sub = tensor - 1 #Or
sub = torch.sub(tensor ,1)

Sub , sub

(tensor([0, 1, 2]), tensor([0, 1, 2]))

In [ ]:
Mul = tensor  *11  #Or
mul = torch.mul(tensor , 11)

Mul  , mul

(tensor([11, 22, 33]), tensor([11, 22, 33]))

## 🔸 Matrix Multiplication.



Two main ways of performing muliplication in neural networks and deep learning:



1. Element-wise multiplication

2. Marix multiplication(dot product)

In [ ]:
# Create element wise multiplication
print(tensor ,"*" ,tensor)
print("Equals:" ,tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Create matrix multiplication
mul_value = torch.matmul(tensor , tensor)

mul_value

tensor(14)

**Note**: let's see wall time when we use `loop` , `matmul` ,`mm` ,`bmm` , `@` in Matrix Multiplication.

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 1.8 ms


tensor(14)

In [ ]:
%%time
mat_value = torch.matmul(tensor ,tensor)

mat_value

CPU times: user 720 µs, sys: 0 ns, total: 720 µs
Wall time: 557 µs


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 180 µs, sys: 0 ns, total: 180 µs
Wall time: 191 µs


tensor(14)

## 🔸 One of the most common errors in deep learning (shape errors).  

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
# That will return RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.



One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor).



You can perform transposes in PyTorch using either:



* torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

* tensor.T - where tensor is the desired tensor to transpose.

In [ ]:
print(tensor_A.shape ," , " ,tensor_B.shape)

torch.Size([3, 2])  ,  torch.Size([3, 2])


In [ ]:
# View tensor_A and tensor_B
tensor_A ,tensor_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [ ]:
# View tensor_A and tensor_B.T
tensor_A ,tensor_B.T

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [ ]:
# The operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")

Output = tensor_A @ tensor_B.T
#Output = torch.matmul(tensor_A ,tensor_B.T)
print(Output)
print(f"\nOutput Shape: {Output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output Shape: torch.Size([3, 3])


**Note:** You can also use torch.mm() which is a short for torch.matmul().

* Use torch.mm() only for 2D tensors (matrices).

* For batch matrix multiplication of 3D tensors, use torch.bmm().

* sure the dimensions of the tensors are compatible for matrix multiplication:

   - If **A** is (𝑚,𝑛), and **B** is (𝑛,𝑝), the result will be (𝑚,𝑝).

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

**Or we can use first_tensor.mm(sencod_tensor)**

In [ ]:
tensor_A.mm(tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# If you have 3D tensors and need to perform batch matrix multiplication, use torch.bmm() instead. Here’s an example:

tensors_3d = torch.tensor([
                         [[1, 2], [3, 4]],
                         [[5, 6], [7, 8]] ])  # A batch of 2 matrices (2x2 each)

# Perform batch matrix multiplication
result = torch.bmm(tensors_3d, tensors_3d)
print(result)

tensor([[[  7,  10],
         [ 15,  22]],

        [[ 67,  78],
         [ 91, 106]]])


# ◍ Finding the min, max, mean, sum, etc (tensor aggregation).

In [ ]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min in tensor
torch.min(x) , x.min() ,x.min().item() # Find minimum as a single value by use .item() # Output: 1

(tensor(1), tensor(1), 1)

In [ ]:
# Find the max in tensor
torch.max(x) , x.max() , x.max().item() # Find maximum as a single value by use .item() # Output: 91

(tensor(91), tensor(91), 91)

**_`torch.mean(x)`_**

>Note: You may find some methods such as torch.mean() require tensors to be in **torch.float32** (the most common) or another specific datatype, otherwise the operation will fail.


In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)) ,x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
print(x.to(torch.float64).mean().item()) # Or
print(x.float().mean().item())           # Find mean as a single value by use .item() Output: 46.0

46.0
46.0


In [ ]:
# Find the sum
torch.sum(x) , x.sum() ,x.sum().item()

(tensor(460), tensor(460), 460)

# ◍ Finding The position of min ,max values in tensor.

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minmum vlaue with argmin()
min_indx = x.argmin()
print(f"Min value at index : {min_indx}")
print(f"\nMin vlaue : {x[min_indx]}")

Min value at index : 0

Min vlaue : 1


In [ ]:
# Find the position in tensor that has the maxmum vlaue with argmax()
max_indx = x.argmax()
print(f"Max value at index : {max_indx}")
print(f"\nMax vlaue : {x[max_indx]}")

Max value at index : 9

Max vlaue : 91


# ◍ Reshaping, stacking, squeezing and unsqueezing ,permutation.

|Method| One-line description

|:----------:|:----------:

|torch.reshape(input, shape)|	Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`.  

|Tensor.view(shape)|	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.  

|torch.stack(tensors, dim=0)|	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.  

|torch.squeeze(input)|	Squeezes input to remove all the dimenions with value `1`.  

|torch.unsqueeze(input, dim)|	Returns `input` with a dimension value of `1` added at `dim`.  

|torch.permute(input, dims)|	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [ ]:
# Create a tensor
t = torch.arange(1,10)

t ,t.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# Add extra dimension but must eqaul (orignal size)
t_reshaped = t.reshape(1,9)
t_reshaped , t_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
t_reshaped1 = t.reshape(9,1)
t_reshaped1 , t_reshaped1.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = t.view(1,9)
z ,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes t (because a view of a tensor shares the same data as the original input)
z[:,0] = 99
z ,t

(tensor([[99,  2,  3,  4,  5,  6,  7,  8,  9]]),
 tensor([99,  2,  3,  4,  5,  6,  7,  8,  9]))

In [ ]:
# Stack tensors on top of each other
# torch.stack(input can by taple Or list)
t_stacked  = torch.stack([t,t,t] ,dim = 0)
t_stacked ,t_stacked.shape

(tensor([[99,  2,  3,  4,  5,  6,  7,  8,  9],
         [99,  2,  3,  4,  5,  6,  7,  8,  9],
         [99,  2,  3,  4,  5,  6,  7,  8,  9]]),
 torch.Size([3, 9]))

In [ ]:
t_stacked1  = torch.stack([t,t,t] ,dim = 1)
t_stacked1 ,t_stacked1.shape

(tensor([[99, 99, 99],
         [ 2,  2,  2],
         [ 3,  3,  3],
         [ 4,  4,  4],
         [ 5,  5,  5],
         [ 6,  6,  6],
         [ 7,  7,  7],
         [ 8,  8,  8],
         [ 9,  9,  9]]),
 torch.Size([9, 3]))

**` torch.vstack() `**  

* Purpose: Vertically stacks tensors along a new first dimension (dim=0).

* Input Requirement: Tensors must have the same shape, except for the first dimension.

* Shape Change:

   - If tensors have shape `(x, y)`, the result will have shape `(x1 + x2, y)`, where `x1` and `x2` are the first dimensions of the input tensors.

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])  # Shape: (2, 2)
b = torch.tensor([[5, 6]])          # Shape: (1, 2)

result = torch.vstack((a, b))      # Shape: (3, 2)
print(result)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


**` torch.hstack() `**  

* Purpose: Horizontally stacks tensors along the last dimension (dim=1).

* Input Requirement: Tensors must have the same shape, except for the last dimension.

* Shape Change:

  - If tensors have shape `(x, y)`, the result will have shape `(x, y1 + y2)`, where `y1` and `y2` are the second dimensions of the input tensors.

In [ ]:
a = torch.tensor([[1, 2], [3, 4]])  # Shape: (2, 2)
b = torch.tensor([[5], [6]])        # Shape: (2, 1)

result = torch.hstack((a, b))       # Shape: (2, 3)
print(result)

tensor([[1, 2, 5],
        [3, 4, 6]])


In [ ]:
t

tensor([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
# How about removing all single dimensions from a tensor?
# To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).
print(f"Previous tensor: {t_reshaped}")
print(f"Previous shape: {t_reshaped.shape}")

# Remove extra dimension from x_reshaped
t_squeezed = t_reshaped.squeeze()
print(f"\nNew tensor: {t_squeezed}")
print(f"New shape: {t_squeezed.shape}")

Previous tensor: tensor([[99,  2,  3,  4,  5,  6,  7,  8,  9]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([99,  2,  3,  4,  5,  6,  7,  8,  9])
New shape: torch.Size([9])


In [ ]:
# To do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.
print(f"Previous tensor: {t_squeezed}")
print(f"Previous shape: {t_squeezed.shape}")
## Add an extra dimension with unsqueeze

t_unsqueezed = t_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {t_unsqueezed}")
print(f"New shape: {t_unsqueezed.shape}")

Previous tensor: tensor([99,  2,  3,  4,  5,  6,  7,  8,  9])
Previous shape: torch.Size([9])

New tensor: tensor([[99,  2,  3,  4,  5,  6,  7,  8,  9]])
New shape: torch.Size([1, 9])


You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

>Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))
# Permute the original tensor to rearrange the axis order

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
# Or x_permuted = torch.permute(x_original ,(2,0,1))

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 6987

In [ ]:
x_original[0,0,0] , x_permuted[0,0,0]

(tensor(6987.), tensor(6987.))

# ◍ Indexing (selecting data from tensors).

In [ ]:
mat = torch.arange(1,10).reshape(1,3,3)

mat

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
mat[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
mat[0][2][2].item() , mat[:,2,2]

(9, tensor([9]))

In [ ]:
mat[0][0] ,mat[0][1] ,mat[0][2]

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
mat[0][0][0] ,mat[0][0][1] ,mat[0,0,2] ,mat[:,0]

(tensor(1), tensor(2), tensor(3), tensor([[1, 2, 3]]))

In [ ]:
mat[0][1][0] ,mat[0][1][1] ,mat[0][1][2] ,mat[:,1]

(tensor(4), tensor(5), tensor(6), tensor([[4, 5, 6]]))

In [ ]:
mat[0][2][0] ,mat[0][2][1] ,mat[0][2][2] ,mat[:,2]

(tensor(7), tensor(8), tensor(9), tensor([[7, 8, 9]]))

In [ ]:
mat[:,:,0:0] ,mat[:,:,0:1] ,mat[:,:,0:2] ,mat[:,:,0:3]

(tensor([], size=(1, 3, 0), dtype=torch.int64),
 tensor([[[1],
          [4],
          [7]]]),
 tensor([[[1, 2],
          [4, 5],
          [7, 8]]]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

# ◍ PyTorch tensors & NumPy.

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.



The two main methods you'll want to use for NumPy to PyTorch (and back again) are:



* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.  

* **Let's try them out.**

In [ ]:
import torch
import numpy as np
array = np.arange(1.0 ,8.0)

array

array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
numpy_to_tensor = torch.from_numpy(array)
array ,numpy_to_tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

>Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).



>However, many PyTorch calculations default to using float32.



>So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use

**`tensor = torch.from_numpy(array).type(torch.float32).`**

In [ ]:
# Change the values in array ,what will do to `tensor`? -> will not change (Not shared memory).
array = array + 5
array  ,numpy_to_tensor

(array([ 6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor_zeros_num = torch.zeros(8)
tensor_to_numpy  = tensor_zeros_num.numpy()
tensor_zeros_num ,tensor_to_numpy

(tensor([0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

In [ ]:
# Change the values in tensor ,what will do to `array`? -> will not change (Not shared memory).
tensor_zeros_num = tensor_zeros_num +5
tensor_zeros_num ,tensor_to_numpy

(tensor([5., 5., 5., 5., 5., 5., 5., 5.]),
 array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

# ◍ Reproducibility (trying to take the random out of random).

In short how neural networks learns:



`Start with random numbers -> tensor operations -> try to make better again -> again -> again`

In [ ]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A,"\n")
print(random_tensor_B)
print(f"\nDoes Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

tensor([[0.0516, 0.6828, 0.2364, 0.4904],
        [0.5408, 0.2574, 0.4718, 0.5495],
        [0.4136, 0.4115, 0.8356, 0.7439]]) 

tensor([[0.0388, 0.6665, 0.0781, 0.9745],
        [0.6288, 0.7835, 0.9366, 0.4459],
        [0.9306, 0.1452, 0.1857, 0.4114]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(4,3)
random_tensor_D = torch.rand(4,3)

print(random_tensor_C,"\n")
print(random_tensor_D)
print(f"\nDoes Tensor A equal Tensor B? (anywhere)")
random_tensor_C == random_tensor_D

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]]) 

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
# WE Must Set random seed before each random tensor

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(4,3)

torch.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(4,3)

print(random_tensor_E,"\n")
print(random_tensor_F)
print(f"\nDoes Tensor A equal Tensor B? (anywhere)")
random_tensor_E == random_tensor_F

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]]) 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

# ◍ Running tensors on GPUs (and making faster computations).

## 🔸 Getting s GPU.

In [ ]:
!nvidia-smi

Sun Dec 15 01:28:26 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 🔸 Getting PyTorch to run on the GPU.

In [ ]:
import torch
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

Let's create a device variable to store what kind of device is available.

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cuda'

In [ ]:
device = "cuda" if torch.cuda.is_available() else 'cpu'
device # when i turn off gpu

'cpu'

If the above output "cuda" it means we can set all of our PyTorch code to use the available CUDA device (a GPU) and if it output "cpu", our PyTorch code will stick with the CPU.



>Note: In PyTorch, it's best practice to write [device agnostic code](https://pytorch.org/docs/main/notes/cuda.html#device-agnostic-code). This means code that'll run on CPU (always available) or GPU (if available).



If you want to do faster computing you can use a GPU but if you want to do much faster computing, you can use multiple GPUs.



You can count the number of GPUs PyTorch has access to using torch.cuda.device_count().

In [ ]:
# Count number of device
torch.cuda.device_count() # when i turn on gpu

1

In [ ]:
# to know number of devices
torch.cuda.device_count() # when i turn off gpu

0

Knowing the number of GPUs PyTorch has access to is helpful incase you wanted to run a specific process on one GPU and another process on another (PyTorch also has features to let you run a process across all GPUs).

## 🔸 Putting tensors (and models) on GPU.

You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.



Why do this?



GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our **device agnostic code** (see above), it'll run on the CPU.



>**Note**: Putting a tensor on GPU using `to(device)` `(e.g. some_tensor.to(device))` returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:



`some_tensor = some_tensor.to(device)`



Let's try creating a tensor and putting it on the GPU (if it's available).

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1,2,3])

# Tensor Not On GPU by defult in cpu
tensor ,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
# it's return cuda and number of device (there are 1 gpu in my decive ,so it retrun 0 this number of first gpu)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 🔸 Moving Tensors back to CPU.

If tensor on GPU it can't transfrom it to Numpy by **tensor_name.cpu().numpy**

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix this issues we must first set tensor in cpu

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
# Not change
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# ◍ Exercises : [PyTorch Fundamentals Exercises and Solutions](https://github.com/Adnan-Alaref/Pytorch-Tuatorial/blob/main/00_pytorch_fundamentals_exercises.ipynb).

<a id="Import"></a>
<p style="background-color: #000000; font-family: 'Verdana', sans-serif; color: #FFFFFF; font-size: 160%; text-align: center; border-radius: 25px; padding: 12px 20px; margin-top: 20px; border: 2px solid transparent; background-image: linear-gradient(black, black), linear-gradient(45deg, #FF00FF, #00FFFF, #FFFF00, #FF4500); background-origin: border-box; background-clip: content-box, border-box; box-shadow: 0px 4px 20px rgba(255, 105, 180, 0.8);">
   Thanks & Upvote ❤️</p>